export const midWords = [
  "Adlyder",
  "Adskilt Fra",
  "Anbefaler",
  "Angår Ikke",
  "Ansetter",
  "Arbeider Med",
  "Av",
  "Avslutter",
  "Avslår",
  "Bader I",
  "Bak",
  "Bakom",
  "Banker",
  "Barberer",
  "Bearbeider",
  "Bedrar",
  "Bedøver",
  "Begynner Med",
  "Behandler",
  "Ber Om",
  "Beskriver",
  "Bestemmer Innen",
  "Bestiller",
  "Betaler for",
  "Betyr",
  "Binder",
  "Biter",
  "Blir",
  "Bor I",
  "Brekker",
  "Brenner Ned",
  "Bryter Ned",
  "Byr På",
  "Bærer",
  "Bør Ha",
  "Deler",
  "Detter Fra",
  "Diskuterer",
  "Drar Til",
  "Drifter",
  "Drikker",
  "Driver Med",
  "Drømmer Om",
  "Dukker Opp I",
  "Dyrker",
  "Er Blant",
  "Er Bortenfor",
  "Er Den Siste",
  "Er Ennå",
  "Er For Min Del",
  "Er For Tiden",
  "Er Fra Nå Av",
  "Er Fremtiden For",
  "Er Fremtiden I",
  "Er Ikke",
  "Etter",
  "Faller Fra",
  "Finner",
  "Finnes I",
  "Finnes Overalt I",
  "Flyr Til",
  "Flyter Forbi",
  "Foran",
  "Forbi",
  "Forbyr",
  "Foreslår",
  "Foretrekker",
  "Forlater",
  "Forsker På",
  "Forstår Alt Om",
  "Forsvinner Til",
  "Forteller Om",
  "Fra Befolkningen Av",
  "Fra Før",
  "Fra Innsiden Av",
  "Fra Tiden Av",
  "Fra",
  "Fremfor",
  "Fryser På Grunn Av",
  "Fyker Forbi",
  "Fyller Opp",
  "Får",
  "Følger",
  "Før Neste",
  "Før Tiden Av",
  "Før Utgangen Av",
  "Før Valg Av",
  "Før",
  "Først, Deretter",
  "Gir Ikke",
  "Gir",
  "Gjelder",
  "Gjemmer",
  "Gjennom",
  "Gjør Om",
  "Gleder Seg Til",
  "Glemmer Ikke",
  "Glemmer",
  "Glir Forbi",
  "Griner På Grunn Av",
  "Griper",
  "Gråter På Grunn Av",
  "Går For",
  "Går Til",
  "Hadde",
  "Har Angst For",
  "Har Blant Annet",
  "Har",
  "Hender Med",
  "Henger I",
  "Heter",
  "Hilser Til",
  "Hjelper For",
  "Hjelper Med",
  "Holder",
  "Hos",
  "Håper På",
  "I Midten Av",
  "I Nærheten Av",
  "I Retning Av",
  "I Samsvar Med",
  "I",
  "Igjennom",
  "Imot",
  "Inn I",
  "Innen",
  "Innenfor",
  "Inni",
  "Innover Til",
  "Innover",
  "Inntil",
  "Introduserer",
  "Kan Alt Om",
  "Kjenner",
  "Kler",
  "Klipper",
  "Klyper",
  "Knekker",
  "Kommer Til",
  "Koser Seg Med",
  "Kryper Til",
  "Lager",
  "Langs Bakken Av",
  "Langs Med",
  "Langs",
  "Legger",
  "Ler Av",
  "Leter Etter",
  "Lider Av",
  "Ligger I",
  "Ligner",
  "Lyver Om",
  "Med Deres",
  "Med Hjelp Av",
  "Med",
  "Mellom",
  "Midt I",
  "Midt Oppi",
  "Midt Over",
  "Minner Om",
  "Mot",
  "Motsatte",
  "Må Inkludere",
  "Møter",
  "Nedenfor",
  "Nedover",
  "Nyser Av",
  "Nyter",
  "Nær",
  "Nært Innpå",
  "Om",
  "Omkring",
  "Opp Imot",
  "Opp Mot",
  "Opp Til",
  "Opp Under",
  "Oppi",
  "Oppover",
  "Ovenfor",
  "Over",
  "Overdriver",
  "Overfor",
  "Passer Til",
  "Piper Av",
  "Pleier",
  "På Begge Sider Av",
  "På Grunn Av",
  "På Oversiden Av",
  "På Sidelinjen Av",
  "På Tvers Av",
  "På",
  "Rekker Ikke",
  "Renner Fra",
  "Rir Til",
  "River",
  "Roper",
  "Rundt",
  "Ryker Av",
  "Selger",
  "Sender",
  "Ser",
  "Setter",
  "Sier",
  "Sitter I",
  "Skal Til",
  "Skinner I",
  "Skjelver Fra",
  "Skjærer",
  "Skriker Fra",
  "Skriver Om",
  "Skryter Av",
  "Skyldes",
  "Skyter",
  "Skyver Bort",
  "Slipper",
  "Sliter Med",
  "Slår",
  "Slåss Med",
  "Sniker Rundt",
  "Sover I",
  "Spiller",
  "Spinner Rundt",
  "Sprekker I",
  "Spretter Fra",
  "Springer Etter",
  "Spør Om",
  "Steller",
  "Stemmer",
  "Stenger Ned",
  "Stiger Fra",
  "Stikker",
  "Stiller Ut",
  "Stjeler",
  "Stoppet",
  "Strekker",
  "Stryker",
  "Står På",
  "Sviker",
  "Svømmer I",
  "Synger",
  "Synker Fra",
  "Syr",
  "Tar Av",
  "Tar Hensyn Til",
  "Tar",
  "Tenker På",
  "Til Tross For",
  "Til",
  "Tilbyr",
  "Tillater",
  "Treffer",
  "Trekker Ut",
  "Trenger",
  "Trives I",
  "Tørker",
  "Under",
  "Undersøker",
  "Unngår",
  "Ut Av",
  "Uten",
  "Utenfor",
  "Utenfra",
  "Utover Til",
  "Utover",
  "Utvikler",
  "Var Bortom",
  "Ved Hjelp Av",
  "Ved Siden Av",
  "Ved Slutten Av",
  "Ved",
  "Vekk Fra",
  "Velger",
  "Vet Alt Om",
  "Vil Bort Fra",
  "Vil Ta",
  "Vinner",
  "Vrir",
  "Ødelegger",
  "Øker",
  "Ønsker Seg",
];