export const midWords = [
  "adskilt fra",
  "angår ikke",
  "har angst for",
  "tar hensyn til",
  "av",
  "avslutter",
  "bak",
  "bakom",
  "dukker opp i",
  "er blant",
  "er bortenfor",
  "er den siste",
  "er ennå",
  "er for min del",
  "er for tiden",
  "er fra nå av",
  "er fremtiden for",
  "er fremtiden i",
  "først, deretter",
  "på begge sider av",
  "etter",
  "finnes overalt i",
  "foran",
  "forbi",
  "forsker på",
  "fra befolkningen av",
  "fra før",
  "fra innsiden av",
  "fra klassen",
  "fra tiden av",
  "fra",
  "fremfor",
  "følger",
  "før neste",
  "før tiden av",
  "før utgangen av",
  "før valg av",
  "før",
  "gjennom",
  "hadde",
  "har blant annet",
  "har",
  "hos",
  "i midten av",
  "i nærheten av",
  "i retning av",
  "i samsvar med",
  "i",
  "igjennom",
  "imot",
  "inn i",
  "innen",
  "innenfor",
  "inni",
  "innover til",
  "innover",
  "inntil",
  "introduserer",
  "langs bakken av",
  "langs med",
  "langs",
  "ligner",
  "med deres",
  "med hjelp av",
  "med",
  "mellom",
  "midt blant",
  "midt i",
  "midt oppi",
  "midt over",
  "minner om",
  "mot",
  "motsatte",
  "nedenfor",
  "nedover",
  "nær",
  "nært innpå",
  "om",
  "omkring",
  "opp mot",
  "opp til",
  "opp under",
  "opp imot",
  "oppi",
  "oppover",
  "ovenfor",
  "over",
  "overfor",
  "på grunn av",
  "på oversiden av",
  "på sidelinjen av",
  "på tvers av",
  "på",
  "rundt",
  "stoppet",
  "tar av",
  "til tross for",
  "til",
  "under",
  "undersøker",
  "ut av",
  "ut igjennom",
  "uten",
  "utenfor",
  "utenfra",
  "utover til",
  "utover",
  "utvikler",
  "var bortom",
  "ved hjelp av",
  "ved siden av",
  "ved slutten av",
  "ved",
  "vekk fra",
  "vil bort fra",
  "vil ta",
];