export const midWords = [
  "adskilt fra",
  "angår ikke",
  "annen hver",
  "av angst for",
  "av den grunn",
  "av hensyn til",
  "av",
  "avseende",
  "bak",
  "bakenfor",
  "bakfra",
  "bakom",
  "begge sider av",
  "betraktning av",
  "blant",
  "blantannet",
  "bort fra",
  "bortenfor",
  "bortom",
  "bryssel om",
  "den siste",
  "deres",
  "deri",
  "dermed",
  "derpå",
  "derunder",
  "derute",
  "dette",
  "din",
  "ditt",
  "drøyt",
  "dukker opp",
  "dypt inn i",
  "ennå",
  "enormt",
  "enten",
  "etter som",
  "etter",
  "for en",
  "er for min del",
  "er for tiden",
  "foran",
  "forbi",
  "forrige",
  "fra befolkningen av",
  "fra før",
  "fra innsiden av",
  "fra klassen",
  "fra min",
  "fra mitt",
  "er fra nå av",
  "fra og med",
  "fra tiden av",
  "fra",
  "fremfor",
  "er fremtiden for",
  "er fremtiden i",
  "følgende",
  "før dagen er",
  "før neste",
  "før tiden av",
  "før utgangen av",
  "før valg av",
  "før",
  "først i",
  "først til å",
  "ganske mye",
  "ganske så",
  "gjennom",
  "tar gjennomgang av",
  "har gjennomgang til",
  "er gjennomsnittlig",
  "hos",
  "i følge",
  "i midten av",
  "i nærheten av",
  "i retning av",
  "i samsvar med",
  "i øyeblikket av",
  "i",
  "ifølge",
  "igjennom",
  "imot",
  "inn i",
  "innen",
  "innenfor",
  "inni",
  "innover til",
  "innover",
  "inntil",
  "langs bakken av",
  "langs med",
  "langs",
  "langsforbi",
  "med hjelp av",
  "med",
  "mellom",
  "midt blant",
  "midt i",
  "midt oppi",
  "midt over",
  "mot",
  "motsatte",
  "nedenfor",
  "nedenfortil",
  "nedover",
  "nær",
  "nært innpå",
  "om",
  "omkring",
  "omkringom",
  "opp mot",
  "opp til",
  "opp under",
  "oppi mot",
  "oppi",
  "oppover",
  "ovenfor",
  "over",
  "finnes overalt i",
  "overfor",
  "overimot",
  "på grunn av",
  "på oversiden av",
  "på sidelinjen av",
  "på tvers av",
  "på tvers",
  "på",
  "rundt og rundt",
  "rundt",
  "rundtomkring",
  "til tross for",
  "til",
  "under",
  "underveis",
  "ut av",
  "ut igjennom",
  "uten",
  "utenfor",
  "utenforfor",
  "utenfra",
  "utenifra",
  "utover til",
  "utover",
  "ved hjelp av",
  "ved siden av",
  "ved siden",
  "ved skog og mark",
  "ved slutten av",
  "ved",
  "vekk fra",
  "vil ta",
];