export const preWords = [
  "Sverige",
  "Danmark",
  "Finland",
  "Oslo",
  "Island",
  "Skandinavia",
  "Trondheim",
  "Russland",
  "Grønland",
  "Tyskland",
  "Svalbard",
  "Nato",
  "Statoil",
  "Europa",
  "Norsk",
  "Østerrike",
  "Belgia",
  "Den Første",
  "Den Siste",
  "Den Andre",
  "Bergen",
  "Skagerrak",
  "Irland",
  "Ukraina",
  "Polen",
  "Stavanger",
  "Nigeria",
  "København",
  "Sveits",
  "Hellas",
  "Holland",
  "Nynorsk",
  "Konstitusjonelt",
  "Nederland",
  "Moskva",
  "Frankrike",
  "Samiske",
  "India",
  "Bokmål",
  "Nederlandsk",
  "Norge",
  "Nordsjøen",
  "Kalmarunionen",
  "Noreg",
  "Kamerun",
  "Litauen",
  "England",
  "Algeria",
  "Norge",
  "Kroatia",
  "Nidaros",
  "Sognefjord",
  "Svartedauden",
  "Barentshavet",
  "Monarchy of",
  "Unitary",
  "Parliament of",
  "Norwegian",
  "Human",
  "Canada",
  "Sveits",
  "Fremskrittspartiet",
  "Kypros",
  "EU",
  "Bulgaria",
  "Malta",
  "Armenia",
  "Australia",
  "Uganda",
  "Serbia",
  "Ungarn",
  "Egypt",
  "Svensk",
  "Usa",
  "Storbritannia",
  "Kosovo",
  "Dublin",
  "Kingdom",
  "Scandinavian",
  "Andre",
  "The",
  "Northern",
  "Antarctica",
  "Romania",
  "Albania",
  "Hus",
  "Brun",
  "Bahrain",
  "Alaska",
  "Kenya",
  "Japan",
  "Oslo Norway",
  "Tsjekkoslovakia",
  "Eea",
  "Swedes",
  "Palestina",
  "Faroes",
  "Church Of Norway",
  "Nrk",
  "Scandinavians",
  "Skottland",
  "Brasil",
  "Russisk",
  "Dansk",
  "Latvia",
  "Mexico",
  "Portugal",
  "Bernie",
  "Ny",
  "Efta",
  "Finnmark",
  "Statoilhydro",
  "Elg",
  "Helsingborg",
  "Fugl",
  "Rosenborg",
  "Aarhus",
  "Laks",
  "Nordisk",
  "norsk",
  "Tyrkia",
  "Kina",
  "Storbritannia",
  "Arktisk",
  "Islandsk",
  "Peter I Island",
  "Afghanistan",
  "Morten",
  "Bouvet Island",
  "Topography",
  "Queen Maud Land",
  "House Of Glücksburg",
  "Erna Solberg",
  "Nordea",
  "Supreme Court Of Norway",
  "Vikings",
  "Slovenia",
  "Fastland",
  "Jens Stoltenberg",
  "finsk",
  "Fjord",
  "Hviterussland",
  "Qatar",
  "Tundra",
  "Europeisk",
  "Tsjekkisk",
  "United",
  "Battle Of Hafrsfjord",
  "Jesper",
  "Sametinget i Norge",
  "Stockholm Sverige",
  "USA",
  "finner",
  "Europarådet",
  "Forente nasjoner",
  "Nordisk",
  "Økonomisk",
  "Luxembourg",
  "Bruttonasjonalprodukt",
  "Social sikkerhet",
  "Midtøsten",
  "Malmö",
  "Reykjavik",
  "Handelsbanken",
  "Middle Latin",
  "Hungersnød",
  "Ordfører",
  "Goteborg",
  "Romantikk",
  "Islendinger",
  "Drammen",
  "Daner",
  "Iron Age",
  "Malmo",
  "Uppsala",
  "Northern Europe",
  "Christianization Of Scandinavia",
  "Aalborg",
  "Hanseatic League",
  "Helsinki",
  "Union Between Sweden And Norway",
  "Fc Copenhagen",
  "Odense",
  "Olaf Ii Of Norway",
  "Austrians",
  "Turku",
  "Personlig forening",
  "Brondby",
  "Østersjøen",
  "Tsjekkere",
  "Glacier",
  "Bosnia Hercegovina",
  "Kalkstein",
  "Henrik Wergeland",
  "Peter Christen Asbjørnsen",
  "Nordiske",
  "Marine",
  "Hydro",
  "Kvinners",
  "Egalitarisme",
  "Arbeiderparti",
  "Mineral",
  "Færøyene",
  "Telenor",
  "Estland",
  "Immigration",
  "Gro Harlem Brundtland",
  "Høyre",
  "Sovereign Wealth Fund",
  "Monarchy",
  "Aurora",
  "Erik",
  "Shetland",
  "Orknøyene",
  "Golfstrømmen",
  "Storting",
  "Rain Shadow",
  "Mineraler",
  "Sjømat",
  "Tømmer",
  "Stockholm",
  "Peninsula",
  "Geats",
  "Imf",
  "Filologi",
  "Gøteborg",
  "Strædet",
  "Normannere",
  "Geopolitisk",
  "Rogaland",
  "Norseman",
  "Lofoten",
  "Christiania",
  "Naze",
  "Trøndelag",
  "Indonesia",
  "Malaysia",
  "Harstad",
  "Bronse",
  "Slovakia",
  "Belize",
  "Gallia",
  "Den Franske",
  "Arkeologi",
  "Runer",
  "Bornholm",
  "Kiribati",
  "Dominica",
  "Grenada",
  "Høvding",
  "Haiti",
  "Klaner",
  "Hordaland",
  "Stamme",
  "Ting",
  "Surinam",
  "Brunei",
  "Fiji",
  "Tyrol",
  "Uruguay",
  "Bahamas",
  "Bolivia",
  "Barbados",
  "Guyana",
  "Venezuela",
  "Mauritius",
  "Lesotho ",
  "Cuba",
  "Jamaica",
  "Proporsjonal",
  "Angola",
  "Friesland",
  "Chile",
  "Nauru",
  "Bangladesh",
  "Anguilla",
  "Etruria",
  "Countrywide",
  "Ecuador",
  "Bhutan ",
  "Vanuatu",
  "Tuvalu",
  "Botswana",
  "Komorene",
  "London",
  "Ahrensburg",
  "Samoa",
  "Palau",
  "Bermuda",
  "Rwanda",
  "Transalpine",
  "Lindesnes",
  "Paraguay",
  "Tonga",
  "Vietnam",
  "USSR",
  "Mikronesia",
  "Zimbabwe",
  "Maldivene",
  "Karibien",
  "Kambodsja",
  "Argentina",
  "Burundi",
  "Moldavia",
  "Amerika",
  "Yemen",
  "Proto",
  "Jämtland",
  "Troms",
  "Kingdom of",
  "Moldova",
  "Mozambique",
  "Napoleon",
  "Mali",
  "Iran",
  "G8",
  "Benin",
  "Malawi",
  "Transkaukasia",
  "Filippinsk",
  "Namibia",
  "Ru",
  "Lillehammer",
  "Tasmania",
  "Australsk",
  "Syria",
  "Montenegro",
  "Zambia",
  "Libanon",
  "Turkmenistan",
  "Andorra",
  "Horder",
  "Uavhengig",
  "Anders ",
  "Liberia",
  "Sardinia",
  "Hörgr",
  "Trondheimsfjord",
  "Madagaskar",
  "Aruba",
  "Romsdalsfjord",
  "Kashmir",
  "Reich",
  "Gujarat",
  "Gambia",
  "Israel",
  "Sydney",
  "Danmark-norge",
  "Mauritania",
  "Iberia",
  "Kirgisistan",
  "Tadsjikistan",
  "Kuwait",
  "Bavaria",
  "Rotherhithe",
  "Campania",
  "Fædreland",
  "Ikke-land",
  "Pakistan",
  "Oslofjord",
  "Colombia",
  "Landsløst",
  "Niger",
  "Suveren",
  "Skandinaviske",
  "Aserbajdsjan",
  "Dependencies of",
  "Countrylike",
  "Bohuslän",
  "Czechia",
  "Härjedalen",
  "Island",
  "Separate",
  "Cabinet of",
  "Election for",
  "Kingdoms of",
  "Samisk",
  "Tsjekkia",
  "Felles",
  "Baltisk",
  "Antarktisk",
  "Det Europeiske",
  "Tyrkisk",
  "Nordisk",
  "Universal",
  "Ungarsk",
  "Makedonia",
  "Ankara",
  "Østerriksk",
  "Marokko",
  "Breddegrad",
  "Verdensbanken",
  "Alger",
  "Insekt",
  "Lichen",
  "Sentral",
  "Moss",
  "Moldova",
  "Gammelnorsk",
  "Invertebrate",
  "Kypriotisk",
  "EU",
  "Liechtenstein",
  "Molde",
  "Vemork",
  "Kasakhstan",
  "Det Britiske",
  "Lav",
  "Gammelengelsk",
  "Ghana",
];